-- Create EducationalDetails table
CREATE TABLE IF NOT EXISTS EducationalDetails (
    id INT AUTO_INCREMENT PRIMARY KEY,
    studentId VARCHAR(20) NOT NULL UNIQUE,
    collegeName VARCHAR(255) NOT NULL,
    degree VARCHAR(100) NOT NULL,
    stream VARCHAR(100) NOT NULL,
    yearOfPassing INT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (studentId) REFERENCES Student(studentId) ON DELETE CASCADE
);
